import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    description: "High-quality wireless headphones with noise cancellation and 30-hour battery life",
    price: 199.99,
    originalPrice: 299.99,
    discount: 33,
    image: "/premium-wireless-headphones.png",
    category: "electronics",
    stock: 15,
  },
  {
    id: "2",
    name: "Smart Fitness Watch",
    description: "Track your fitness goals with this advanced smartwatch featuring heart rate monitoring",
    price: 249.99,
    image: "/smart-fitness-watch.png",
    category: "electronics",
    stock: 23,
  },
  {
    id: "3",
    name: "Designer Leather Jacket",
    description: "Genuine leather jacket with modern design and premium craftsmanship",
    price: 399.99,
    originalPrice: 599.99,
    discount: 33,
    image: "/designer-leather-jacket.jpg",
    category: "fashion",
    stock: 8,
  },
  {
    id: "4",
    name: "Running Shoes Pro",
    description: "Professional running shoes with advanced cushioning and breathable material",
    price: 129.99,
    image: "/professional-running-shoes.png",
    category: "sports",
    stock: 42,
  },
  {
    id: "5",
    name: "Modern Table Lamp",
    description: "Elegant table lamp with adjustable brightness and contemporary design",
    price: 79.99,
    originalPrice: 119.99,
    discount: 33,
    image: "/modern-table-lamp.jpg",
    category: "home",
    stock: 18,
  },
  {
    id: "6",
    name: "Portable Bluetooth Speaker",
    description: "Waterproof portable speaker with 360-degree sound and 12-hour battery",
    price: 89.99,
    image: "/portable-bluetooth-speaker.jpg",
    category: "electronics",
    stock: 31,
  },
  {
    id: "7",
    name: "Casual Cotton T-Shirt",
    description: "Comfortable cotton t-shirt with modern fit and premium fabric",
    price: 29.99,
    image: "/casual-cotton-tshirt.jpg",
    category: "fashion",
    stock: 67,
  },
  {
    id: "8",
    name: "Yoga Mat Premium",
    description: "Extra thick yoga mat with non-slip surface and carrying strap",
    price: 49.99,
    originalPrice: 79.99,
    discount: 37,
    image: "/premium-yoga-mat.png",
    category: "sports",
    stock: 25,
  },
  {
    id: "9",
    name: "Ceramic Coffee Mug Set",
    description: "Set of 4 handcrafted ceramic mugs with unique designs",
    price: 39.99,
    image: "/ceramic-coffee-mug-set.png",
    category: "home",
    stock: 44,
  },
  {
    id: "10",
    name: "Wireless Keyboard & Mouse",
    description: "Ergonomic wireless keyboard and mouse combo with long battery life",
    price: 69.99,
    image: "/wireless-keyboard-mouse.png",
    category: "electronics",
    stock: 19,
  },
  {
    id: "11",
    name: "Denim Jeans Classic",
    description: "Classic fit denim jeans with premium denim and comfortable stretch",
    price: 79.99,
    originalPrice: 119.99,
    discount: 33,
    image: "/classic-denim-jeans.jpg",
    category: "fashion",
    stock: 36,
  },
  {
    id: "12",
    name: "Tennis Racket Pro",
    description: "Professional tennis racket with carbon fiber frame and perfect balance",
    price: 159.99,
    image: "/professional-tennis-racket.jpg",
    category: "sports",
    stock: 12,
  },
]
